version: "3.5"

services:
  postgres:
    container_name: postgres_container
    build:
      context: ./app
      dockerfile: postgres.Dockerfile
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - 5432
    restart: unless-stopped

  backend:
    container_name: aspire_backend
    build:
      context: ./app
    depends_on:
      - postgres
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
    postgres: